---
title: 'Project Milestone #1'
author: "Cian Stryker"
date: "2/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

I'm considering doing my project on a recent published article titled "Ethnic Riots and Prosocial Behavior: Evidence from Kyrgyzstan". This paper is within my region of focus but is also one of the few papers that takes a quantitative approach to Central Asian studies. It attempts to measure the effect of the ethnic riots of 2010 in Osh, Kyrgyzstan had on overall prosocial behavior. It relies on an extensive survey that the researchers preformed in Osh, but this data is available. I am concerned that because it is not an observational study, however, that I may be limited in expanding the paper myself. The main statistical techinques used are OLS regressions. 

I'm also considering tackling the paper, "Mass Repression and Political Loyalty: Evidence from Stalin's 'Terror by Hunger'", which is a study of the repressive effect of Stalin's use of famine against Ukraine. It includes five measures of political loyalty and spans from 1940 to 2017. It's a great paper and all the data is available so I should be able to replicate its OLS regressions easily. I'm not sure how I would expand on the paper though. 